- README.md
I updated the ReadMe to include the group members and what roles we have, and setup for when we come up with project name and description.
> #5 Read Me

- MeetingNotes/BranchInTerminal.md
You can see what git branch you are on without having to do git status. Can show y'all Wednesday if you would like
> Bash Profile Change

- BackendPkg/GroceryStore.go
- BackendPkg/Ingredient.go
- BackendPkg/Recipe.go
Created 3 struct files based on the struct hierarchy
> added basic struct layout

- BackendPkg/FoodItem.go
- BackendPkg/Pantry.Go
> added basic struct layouts

- ClassNotes/1-25-23ClassNotes.md
Notes from class 1/25
User stories help define functionality. He was saying he wants them for Sprint 0.
> User Story Notes Class 1/25

- BackendPkg/FoodItem.go
- BackendPkg/Pantry.Go
- BackendPkg/Recipe.go
Finished the functions for a pantry, and added a function for FoodItem
> Finished Pantry Functions

- BackendPkg/Pantry.Go
added time in the pantry struct and update time each time an item is added/removed
> added time in pantry struct

- main.go
> adding main package

- BackendPkg/FoodItem.go
- BackendPkg/Ingredient.go
- BackendPkg/Recipe.go
> more changes

- BackendPkg/FoodItem.go
- BackendPkg/GroceryStore.go
- BackendPkg/Ingredient.go
- BackendPkg/Pantry.Go
- BackendPkg/Recipe.go
> changes package name

- BackendPkg/FoodItem.go
- BackendPkg/GroceryStore.go
- BackendPkg/Ingredient.go
- BackendPkg/Pantry.Go
- BackendPkg/Recipe.go
changed all struct variables to capital letters so they can be accessed outside of the struct
> changed all struct variables to capital letters

- BackendPkg/go.mod
- go.mod
- main.go
> added mode and main files

- BackendPkg/go.mod
- go.mod
- main.go
> New mod updates

- BackendPkg/FoodItem.go
- BackendPkg/Pantry.go
- BackendPkg/go.mod
- go.mod
- main.go
> connected module to main

- BackendPkg/Pantry.go
- main.go
> main to backend functions!

- ClassNotes/2-1-2023.md
- spoke a lot of using more unit tests and how to implement them
- also a killer quote about mushrooms
> Feb 1 Class

- Saucier720-app/src/app/pantry/pantry.component.html
- Saucier720-app/src/app/pantry/pantry.component.scss
I added two new sidebars for the quantity and price of the ingredients and it matches the wireframe rough draft(pdf in the documentation folder)
This continues issue #56
> #56 Wireframe Rough Draft

- Saucier720-app/deploy.sh
Added a deploy script because we merged wrong and the other disappeared
> Deploy scipt

- main.go
> edited main for testing

- Saucier720-app/src/app/app-routing.module.ts
- Saucier720-app/src/app/app.component.html
- Saucier720-app/src/app/app.component.ts
- Saucier720-app/src/app/core/interfaces/ingredient.ts
- Saucier720-app/src/app/core/interfaces/pantry.ts
- Saucier720-app/src/app/core/services/http.service.ts
- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/deals/deals.component.html
- Saucier720-app/src/app/list/list.component.html
- Saucier720-app/src/app/mocks/ingredients.mock.ts
- Saucier720-app/src/app/pantry/pantry.component.html
- Saucier720-app/src/app/pantry/pantry.component.ts
- Saucier720-app/src/app/recipes/recipes.component.html
- Saucier720-app/src/app/testing/app.component.spec.cy.ts
- Saucier720-app/src/app/testing/http.service.spec.cy.ts
- Saucier720-app/src/app/testing/ingredient.service.spec.cy.ts
- Saucier720-app/src/app/testing/pantry/pantry.component.spec.cy.ts
- Saucier720-app/src/app/testing/pantry/pantry.service.spec.cy.ts
- deploy.sh
We have the html client ready to be merged with the backend files. It is currently sending a request to `localhost:4200/api/Pantry`. If we get the backend to send a request we receive it with the frontend and then we can display it.
#105
> Html Client

- src/BackendPkg/UnitTest.go
Merging unit test for backend into Connect
> First unit test

- Saucier720-app/src/app/core/services/ingredient.service.ts
- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
Errors did not arise from improper mocks yesterday.
> Updated Mocks

- Saucier720-app/src/app/testing/pantry/pantry.component.spec.cy.ts
Testing HTML output for the headers in pantry
> Html Tests

- Saucier720-app/deploy.sh
The script was incorrect. I think this change was already merged but want to clean up the branches before sprint 3 starts. This script just deploys the page to github.io
> Deploy Script

- .gitmodules
> Adding google golang submod

- .gitmodules
> new changes

- Other/BackendFrontendCommunication/SubmoduleInit.md
added markdown instructions for submodules
> added instructions for first install

- Other/BackendFrontendCommunication/SubmoduleInit.md
> new updates

- Other/BackendFrontendCommunication/SubmoduleInit.md
> doc changes

- Other/BackendFrontendCommunication/SubmoduleInit.md
- src/BackendPkg/Scraper.go
- src/SeleniumDrivers/chromedriver_win32/LICENSE.chromedriver
added chromedriver for windows
> im so silly

- src/TestingFiles/SeleniumDrivers/chromedriver_win32/LICENSE.chromedriver
copied windows chromedriver to testing folder
> moved windows.exe

- Other/CommonError.md
added common errors markdown file
> added common errors md file

- .gitignore
- .gitmodules
Updated gitignore to not commit files in submodules and updated the name of the first `protobuf` to `protobuf1` so that submodules can initialize properly.
#170
> Update GitIgnore and GitModules

- src/BackendPkg/Database.go
- src/main.go
changed the db name to represent changes
> Changed the database name

- src/main.go
> it works now, the database data is going to frontend

- src/main.go
Deleted second time in main.go. Probably from the merge conflicts yesterday.
> Remove double time

- goTest.sh
Created a bash file to auto run all tests
#176
> Backend Bash Test File

- build.sh
- go.sh
- serve.sh
The bash script `build.sh` calls `serve.sh` and `go.sh` to create an instance of the frontend and backend from one script.
#137
> New Bash Script to Run both Frontend and Backend in Parallel

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.html
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.spec.ts
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.ts
- Saucier720-app/src/app/deals/deals.component.html
- Saucier720-app/src/app/deals/deals.component.ts
I made further changes on the `Deals` page and am now using bootstrap. 
#173
> Deals Page BootStrap Update

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/deals/deals.component.html
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.spec.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
- Saucier720-app/src/app/pantry/pantry.component.html
- Saucier720-app/src/app/pantry/pantry.component.ts
I updated Pantry to use Bootstrap and ease of further changes 
#173
> Pantry Bootstrap Update

- Saucier720-app/src/app/app-routing.module.ts
- Saucier720-app/src/app/app.component.html
- Saucier720-app/src/app/app.component.scss
Added a button so that login page is accessible from the topnav bar
#93
> Login Page Button

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.html
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.spec.ts
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.ts
- Saucier720-app/src/app/deals/deals.component.html
- Saucier720-app/src/app/deals/deals.component.ts
> Boot strap update

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.spec.ts
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
- Saucier720-app/src/app/pantry/pantry.component.html
- go.sh
- src/BackendPkg/Router.go
- src/main.go
New button that posts data(currently hard coded example). The backend then responds (with all the data from the database currently). We can continue with this and have the backend update the database to have a new item stored for users.
#203
> Post New Pantry Item

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.html
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.ts
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.spec.ts
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
- Saucier720-app/src/app/pantry/pantry.component.html
- go.sh
- src/BackendPkg/Router.go
- src/main.go
> Use Template Files instead of template in the typescript component

- src/BackendPkg/Database.go
> made fxn to read user data from db

- src/BackendPkg/GroceryStore.go
- src/TestingFiles/DealsDb_test.go
- src/main.go
Adjusted scraping so that we consistently start without a hard-coded value
> New scrape

- Other/BackendDocumentation/Testing.md
> fixed testing doc

- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/mocks/pantry.mock.ts
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
- src/BackendPkg/Database.go
- src/BackendPkg/Router.go
- src/main.go
Implemented a new post button on the `/Pantry` page. When this button is pushed it sends a current hardcoded FoodItem from the frontend and adds it to the backend database. There is so more optimization with organization to optimize this functionality. @rileycleavenger @samforstot I will leave this branch open. If y'all could go through my go code and either refactor or help me refactor that would be great.
#203 #206
> Post to Database from Frontend

- Saucier720-app/src/app/login/login.component.html
- Saucier720-app/src/app/signup/signup.component.html
> updated routing links

- Saucier720-app/package-lock.json
- Saucier720-app/package.json
Ran a npm audit fix and updated cypress
> Cypress and Npm Update

- Saucier720-app/src/app/app-routing.module.ts
- Saucier720-app/src/app/core/services/Auth/auth.guard.service.spec.ts
- Saucier720-app/src/app/core/services/Auth/auth.guard.service.ts
- Saucier720-app/src/app/core/services/Auth/auth.service.spec.ts
- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/login/login.component.ts
Setup authentication services and guards for the login page
#234
> User login setup for Frontend

- src/BackendPkg/Database.go
- src/BackendPkg/Recipe.go
- src/colors.json
- src/main.go
Figured out how to read in json files that have specific formats
> Basic read in

- src/BackendPkg/Database.go
- src/BackendPkg/Recipe.go
- src/main.go
Finished the read in files for the recipes.json file
> New recipes branch

- src/main.go
> this one works fr fr fr fr

- src/main.go
> recipes file

- src/BackendPkg/Database.go
> deleted empty values from the table

- src/BackendPkg/Database.go
- src/BackendPkg/Recipe.go
- src/BackendPkg/Recommendation.go
- src/main.go
made the recommendation struct to return recommended recipies
> Compare recipe

- src/BackendPkg/Recommendation.go
did not want to forget the plan for tomorrow because it is mad late lol
> plan with best func

- src/BackendPkg/Recommendation.go
- src/BackendPkg/Router.go
- src/BackendPkg/User.go
- src/main.go
> Signup read

- .gitignore
- Saucier720-app/package-lock.json
- Saucier720-app/package.json
- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.html
- Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.scss
- Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.spec.ts
- Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.ts
- Saucier720-app/src/app/signup/signup.component.html
- src/go.mod
- src/go.sum
Needed to ask for new user data on the signup page, broke it down to bare bones as we will be redoing.
> Signup Form

- src/BackendPkg/FoodItem.go
- src/BackendPkg/Router.go
- src/BackendPkg/User.go
- src/main.go
> sign up posting works

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/core/interfaces/user.ts
- Saucier720-app/src/app/signup.service.ts
- Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.html
- Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.ts
- Saucier720-app/src/app/signup/signup.component.ts
- src/BackendPkg/Router.go
We can now post new Users from the frontend to the MealDealz database
#234
> Signup Connection

- src/BackendPkg/Database.go
- src/BackendPkg/Router.go
- src/main.go
> changes made

- src/BackendPkg/Router.go
changed it to read "Ingredient"
> should read post correctly

- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
Need to change the post request
> Json content

- src/BackendPkg/Database.go
- src/BackendPkg/Router.go
- src/main.go
now it refreshes with new pantry items
> what typescript

- src/BackendPkg/Router.go
> new router functions for each page for different global vars

- src/BackendPkg/Router.go
- src/BackendPkg/User.go
> made func to read user login and validation function

- Saucier720-app/package-lock.json
- Saucier720-app/package.json
- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/login/login.component.ts
> Login page cookies

- Saucier720-app/src/app/login/login.component.ts
- src/BackendPkg/Database.go
- src/BackendPkg/User.go
As the great Riley once said "read the title"
> Gen cookies

- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
- Saucier720-app/src/app/pantry/pantry.component.html
- Saucier720-app/src/app/pantry/pantry.component.scss
Added bootstrap and some css to new pantry item field
> Button Organization

- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/login/login.component.ts
- src/BackendPkg/Database.go
- src/BackendPkg/Router.go
- src/BackendPkg/User.go
- src/main.go
The login page receives cookies from the backend!!
> Cookie service

- Saucier720-app/src/app/login/login.component.ts
removed console logs that were used for testing
> some changes

- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- src/main.go
> made minor changes

- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/login/login.component.html
- Saucier720-app/src/app/login/login.component.ts
The login page now has functionality to login directly on the login page. Also checks if logged in to access other pages.
> Login form

- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- src/BackendPkg/Router.go
> Cookie two

- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/core/interfaces/recipe.ts
- Saucier720-app/src/app/core/services/recipes/recipe.service.ts
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
- Saucier720-app/src/app/recipes/recipes.component.html
- Saucier720-app/src/app/testing/core/services/recipe.service.spec.cy.ts
- Saucier720-app/src/app/testing/recipes/recipe-card.component.spec.cy.ts
Created recipes page that gets user data
#84
> Recipes Page data

- src/BackendPkg/Database.go
- src/BackendPkg/Router.go
- src/main.go
Only allows 1 login per session tho, need to fix main
> User cookies

- src/BackendPkg/Router.go
- src/main.go
tried allowing users to login after someone is logged in and update data accordingly, but doesn't work yet, but still runs the single user
> multiple logins in one session

- src/BackendPkg/Router.go
> Sending data

- Saucier720-app/src/app/core/interfaces/recipe.ts
- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
Displays recipe page title data
#84
> Recipe Page Displays Title of Each

- Saucier720-app/src/app/app.component.scss
> Navbar is absolute and scrolls with page

- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
> Working incrementing buttons

- Saucier720-app/src/app/core/interfaces/recipe.ts
- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- src/BackendPkg/Router.go
> Recipe cards

- Saucier720-app/src/app/core/interfaces/recipe.ts
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
Properly receives data from backend
#84
> display recipe data

- src/BackendPkg/Router.go
- src/main.go
I had to rework main.go to allow for multiple users to login/logout/login in a single session
> Cancel go routines

- src/main.go
It functions but it breaks sometimes!
> Users functioning

- src/BackendPkg/Router.go
> now displays recipes based on user

- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/login/FEC/login-form/login-form.component.ts
- src/BackendPkg/Router.go
The login form now sets the cookie, the auth service checks if the cookie is set, if the cookie is set it continues to set the user to logged in and continue allowing access to the other pages
#234
> Login form sets the cookie

- Saucier720-app/src/app/login/FEC/login-form/login-form.component.html
- Saucier720-app/src/app/login/FEC/login-form/login-form.component.ts
> Login instead of submit

- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
Recipe card now displays instructions and ingredients
#289
> Recipe instructions

- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
- Saucier720-app/src/app/pantry/pantry.component.html
- Saucier720-app/src/app/pantry/pantry.component.scss
Can now send updated pantry to the backend
#229
> Update pantry with buttons!

- src/BackendPkg/Database.go
- src/BackendPkg/Router.go
added a listen function for pantry updates
> Pantry updates

- Saucier720-app/src/app/core/services/pantry/pantry.service.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
- src/BackendPkg/Router.go
Can now update pantry in the backend with the buttons
> Listen pantry updates

- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
If the pantry item has 0 quantity it will be deleted when we update the pantry
> Delete pantry item

- src/BackendPkg/Router.go
- src/main.go
the backend works for multiple users now!!!!
> Backend go updates

- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
Created a pantry button that puts the item quantity to 0
> Pantry delete item button

- src/BackendPkg/Database.go
- src/BackendPkg/Recipe.go
- src/BackendPkg/Scraper.go
- src/main.go
> Fixing recipes

- Saucier720-app/src/app/login/FEC/login-form/login-form.component.ts
- src/BackendPkg/Router.go
changed the rout pantry func to be a goroutine within a goroutine
> it works without any errors now

- src/BackendPkg/Router.go
now updates recipes when it updates your pantry
> now updates recipes when it updates your pantry

- src/BackendPkg/Recipe.go
- src/main.go
> testing functionality hi

- src/TestingFiles/JsonRead_test.go
- src/TestingFiles/recipes.json
Added a test for reading json file
> created json reading test

- Saucier720-app/cypress/e2e/HttpRequests/pantry.http.spec.cy.ts
- Saucier720-app/cypress/support/commands.ts
Added end to end tests for posting pantry items
> E2e pantry testing

- src/TestingFiles/Host_test.go
made a new GET test since we changed how we rout data since the previous sprint
> new GET test

- Saucier720-app/src/app/core/interfaces/recipe.ts
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
> Recipe page overhaul

- src/TestingFiles/GenCookie_test.go
> Gen cookie test

- src/TestingFiles/CancelGo_test.go
> made function to test that canceling ongoing go routines works

- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
> previous button

- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
> fixed pantry type

- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.html
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.scss
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.scss
Made the deals page styled like the rest of the pages
> Style changes

- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
I added a page number at the bottom of the recipes page as well as made the buttons look better.
#346
> Page number

- goTest.sh
> test script

- Saucier720-app/src/app/core/interfaces/recipe.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.scss
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
- Saucier720-app/src/styles.scss
The recipe cards now display info related to the user's pantry and the items on sale
> Recipe cards displaying user info

- go.sh
- goTest.sh
updates the go scripts to not display linker errors on MacOS
> script changes

- Other/BackendFrontendCommunication/HowToRunSprint3.md
- README.md
> updated readme

- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
Fixes an issue described in Issue #374
> now refreshes when you add a new pantry item

- Saucier720-app/src/app/app.component.html
- Saucier720-app/src/app/app.component.ts
- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/core/services/deals/deals.service.ts
- src/BackendPkg/NewRouter.go
- src/main.go
Issue #369
Changed it so when you login the "Login" button changes to "Logout", then when you logout it deletes the cookie and stops routing any user data from the backend. Also when you logout you are rerouted to the login page and can only access that and the signup page and the button for "Logout" changes to "Login". There's a demo in the Discord.
> added a logout button!

- src/BackendPkg/Scraper.go
- src/WalmartScraper.py
Had to check the OS to get the correct driver path for selenium
Closes #412
> had to add an if statement to check the os

- Saucier720-app/src/app/app.component.ts
- Saucier720-app/src/app/app.module.ts
- Saucier720-app/src/app/core/services/recipes/recipe.service.ts
- Saucier720-app/src/app/list/list.component.ts
- Saucier720-app/src/app/login/FEC/login-form/login-form.component.ts
- Saucier720-app/src/app/recipes/FEC/filter-menu/filter-menu.component.html
- Saucier720-app/src/app/recipes/FEC/filter-menu/filter-menu.component.scss
- Saucier720-app/src/app/recipes/FEC/filter-menu/filter-menu.component.ts
- Saucier720-app/src/app/recipes/FEC/new-recipe/new-recipe.component.scss
- Saucier720-app/src/app/recipes/FEC/new-recipe/new-recipe.component.ts
- Saucier720-app/src/app/recipes/FEC/recipe-nav-bar/recipe-nav-bar.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-nav-bar/recipe-nav-bar.component.ts
- Saucier720-app/src/app/recipes/recipes.component.html
- Saucier720-app/src/app/recipes/recipes.component.scss
- Saucier720-app/src/app/recipes/recipes.component.ts
- src/BackendPkg/Database.go
- src/BackendPkg/NewRouter.go
- src/BackendPkg/Recommendation.go
- src/MealDealz.db
Added basic filters for recommended recipes. Users can now select to have their recipes generated from their own recipes and/or all user recipes and/or MealDealz classic (JSON) recipes. 
closes #421
> ENH-421-BasicRecipeFiltering

- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
- src/BackendPkg/Recommendation.go
- src/MealDealz.db
I added a recipe author credit below the title on each recipe card. If it's created by the user it says "Created by <username>" and if it's from the JSON file it says "MealDealz Classic". There's a demo in the Discord.
closes #433
> added recipe author below the title

- Saucier720-app/src/app/deals/FEC/deals-store-button/deals-store-button.component.scss
- Saucier720-app/src/app/deals/FEC/deals-store-button/deals-store-button.component.ts
- src/PublixScraper.py
I managed to get the buttons to highlight depending on what stores deals are being shown. Initializes to walmart and changes accordingly. If we end up keeping track of user clicks then we should keep this in mind for the future so that the page initializes with the specific store rather than our default. 
#420
> Highlight store button

- Saucier720-app/src/app/homepage/FEC/user-dashboard/user-dashboard.component.scss
- Saucier720-app/src/app/homepage/FEC/user-dashboard/user-dashboard.component.ts
> quick fix for adding margins and if no items in pantry

- src/Scrapers/CostcoScraper.py
- src/Scrapers/KrogerScraper.py
Finished the kroger (16 seconds) and costco (58 seconds) scrapers
> Costco and Kroger Scrapers

- Other/BackendDocumentation/SQL/SQL Statements/TableCreation.md
Redid our schema in the backend Azure database
#438
> Azure sql statements

- Saucier720-app/src/app/deals/FEC/deals-store-button/deals-store-button.component.scss
- Saucier720-app/src/app/deals/FEC/deals-store-button/deals-store-button.component.ts
- Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.ts
- Saucier720-app/src/app/deals/deals.component.html
- Saucier720-app/src/app/deals/deals.component.ts
- Saucier720-app/src/app/list/list.component.ts
- Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
- Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
- Saucier720-app/src/app/pantry/pantry.component.html
- Saucier720-app/src/app/pantry/pantry.component.ts
- Saucier720-app/src/app/recipes/FEC/filter-menu/filter-menu.component.ts
- Saucier720-app/src/app/recipes/FEC/new-recipe/new-recipe.component.ts
- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
- Saucier720-app/src/app/recipes/FEC/recipe-nav-bar/recipe-nav-bar.component.html
- Saucier720-app/src/app/recipes/FEC/recipe-nav-bar/recipe-nav-bar.component.ts
- Saucier720-app/src/app/recipes/recipes.component.html
- Saucier720-app/src/app/recipes/recipes.component.ts
- src/BackendPkg/NewRouter.go
- src/Scrapers/KrogerScraper.py
Now the page no longer refreshes when adding items to pantry, list, or scrolling through recipes
#434
> No refresh on pantry list and recipe! 

- Saucier720-app/src/app/core/services/Auth/auth.service.ts
- Saucier720-app/src/app/login/FEC/login-form/login-form.component.html
- Saucier720-app/src/app/login/FEC/login-form/login-form.component.scss
- Saucier720-app/src/app/login/FEC/login-form/login-form.component.ts
I added a loading animation for when the user logs in with a succesful login, and an error message for an invalid login. Demo in the discord
Closes #375
Also did one of the tasks in #472
> Login loading animation and error handling

- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
> fixed the author credit issue

- Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
> got delete button back
